### ISSUE TITLE
Unattached fragment activity

### ISSUE THREAD

**Issue by adelolmo** [adelolmo/mine-sync#9]
```
java.lang.IllegalStateException: Fragment DropboxFragment{3a36046a} not attached to Activity
at android.support.v4.app.Fragment.getResources(Fragment.java:619)
at org.ado.minesync.gui.fragment.DropboxFragment.setViewDropboxAccountLinked(DropboxFragment.java:160)
at org.ado.minesync.gui.fragment.DropboxFragment.access$600(DropboxFragment.java:63)
at org.ado.minesync.gui.fragment.DropboxFragment$DropboxAccountStateListener.onLinkedAccountChange(DropboxFragment.java:280)
at com.dropbox.sync.android.DbxAccountManager$1.onLinkedAccountChange(DbxAccountManager.java:452)
at com.dropbox.sync.android.CoreAccountManager$2.run(CoreAccountManager.java:828)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5274)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

**Comment by adelolmo** [comment]
duplicated
